DROP TABLE IF EXISTS reminders;

CREATE TABLE reminders (
                           id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           reminder_text   VARCHAR(255)   NOT NULL,
                           reminder_date   DATE           NOT NULL,
                           reminder_time   TIME           NOT NULL,
                           created_at      TIMESTAMP      NOT NULL,
                           updated_at      TIMESTAMP      NOT NULL
);

CREATE INDEX idx_reminders_date ON reminders(reminder_date);